default_CONFIG = CONFIG_OC_ETH_ORTE_EXAMPLES=y

ifeq ($(CONFIG_OC_ETH_ORTE_EXAMPLES),y)

SUBDIRS = ping spy hello reliable

endif #CONFIG_OC_ETH_ORTE_EXAMPLES

#############################################################################
# RT-Linux version of build

default_CONFIG = CONFIG_OC_ETH_ORTE_EXAMPLES_RTL=n

ifeq ($(CONFIG_OC_ETH_ORTE_EXAMPLES_RTL),y)

SUBDIRS = hello

endif #CONFIG_OC_ETH_ORTE_EXAMPLES
