IDL_COMPILER=$(USER_BIN_DIR)/orte-idl 

INCLUDES = -I $(USER_OBJS_DIR) 

ifeq ($(CONFIG_OC_ETH_ORTE_IDL),y)

shared_LIBRARIES = ddso

bin_PROGRAMS = ddsop ddsos

ddsop_LIBS =  orte pthread ddso rt
ddsos_LIBS =  orte pthread ddso rt
ifeq ($(TARGET_OS),win32)
ddsop_LIBS +=  ws2_32
ddsos_LIBS +=  ws2_32
endif #TARGET_OS

ddso_SOURCES = ddso_cb.c 
ddso_IDL = ddso.idl
ddsop_SOURCES = ddsop.c
ddsos_SOURCES = ddsos.c

endif #CONFIG_OC_ETH_ORTE_IDL

