default: cvs

cvs:
	autoreconf -i 

all:
	aclocal -I admin 
	autoheader
	automake
	autoconf

dist: VER=$(shell git describe --match='v*' | sed -e 's/^v\(.*\)/\1/')
dist:
	test ! -d orte-$(VER)
	git archive --format=tar --prefix=orte-$(VER)/ HEAD | tar x
	make -C orte-$(VER) -f Makefile.cvs
	tar czf orte-$(VER).tar.gz orte-$(VER)
	cd orte-$(VER) && ./configure && make # Check that we can compile the content of the archive
	@echo "Tarball stored as orte-$(VER).tar.gz"
