/* HelloMessage.java */


/* ********************************************************* *
 *                                                           *
 *                Will be Generated by IDLE                  *
 *                                                           *
 * ********************************************************* */

import java.nio.*;             // For ByteBuffer
import org.ocera.orte.*;



public class HelloMessage extends org.ocera.orte.types.MessageData
{
  private String type;
  private int    maxLength;
  private int    counter = 0;

  public  int cislo;
  public  byte[] retezec = new byte[20];
  //public  String slovo;

  /** constructor  */
  public HelloMessage(Domain dom, /*String newType - generovano podle nazvu souboru z IDLu,*/ int maxLength)
  {
    boolean b;

    this.type      = this.getType();
    this.maxLength = maxLength;

    // type name registration
	if(counter == 0)
    {
	   counter++;
	   data = new byte[maxLength];
	   System.out.println(":j: registruji newDataType: " + this.type); 
	   b = dom.regNewDataType(this.type,maxLength);
       if(b == false)
       {
	     System.out.println(":!j: cannot register new data type!");
         return;
	    }
    }
	System.out.println(":j: instance of HelloMessage created..");
  }


 /**
  * getType - Get type of publication
  * @return type of publication
  */
  public String getType()
  {
    return super.getType();
  }

  // read data
  public void read()
  {
    ByteBuffer bb = ByteBuffer.wrap(data);
	cislo = bb.getInt();
	bb.get(retezec, 0, 20);
  }

  // write data
  public void write()
  {
    ByteBuffer bb = ByteBuffer.wrap(data);
	bb.putInt(cislo);
	bb.put(retezec, 0, 20);
  }


}
