ifeq ($(CONFIG_OC_ETH_ORTE_EXAMPLES),y)

bin_PROGRAMS = orteping

orteping_SOURCES = orteping.c

lib_LOADLIBES =  orte pthread
ifeq ($(OS_TARGET),win32)
lib_LOADLIBES +=  ws2_32
endif #OS_TARGET

endif #CONFIG_OC_ETH_ORTE_EXAMPLES

