ifeq ($(CONFIG_OC_ETH_ORTE_EXAMPLES),y)

bin_PROGRAMS = orteping

orteping_SOURCES = orteping.c

lib_LOADLIBES =  orte pthread
ifeq ($(TARGET_OS),win32)
lib_LOADLIBES +=  ws2_32
endif #TARGET_OS

endif #CONFIG_OC_ETH_ORTE_EXAMPLES

