ifeq ($(CONFIG_OC_ETH_ORTE_EXAMPLES),y)

ifeq ($(CONFIG_OC_ETH_ORTE_EXAMPLES_AS_LIBRARY),y)
INCLUDES += -D MAIN_RENAMED
lib_LIBRARIES = orteping
else
bin_PROGRAMS = orteping
endif

orteping_SOURCES = orteping.c

TARGET_LOADLIBES ?= pthread

lib_LOADLIBES =  orte $(TARGET_LOADLIBES)
ifeq ($(TARGET_OS),win32)
lib_LOADLIBES +=  ws2_32
endif #TARGET_OS

endif #CONFIG_OC_ETH_ORTE_EXAMPLES

