/* getNtpTime.c */

/**
  * This code provides conversion between JAVA a C environments.
  * The C functions are calling here and results are send to JAVA
  * native functions. It uses the header pregenerated by JAVA
  * (by command 'javah -jni class_with_native_function')
  *
  * @author Lukas Pokorny (lukas_pokorny@centrum.cz)
  * @author CTU FEE Prague - Department of Control Engineering (dce.felk.cvut.cz)
  * @author Project ORTE - OCERA Real Time Ethernet (www.ocera.org)
  * @author dedication to Kj
  * @version 0.1
  *
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  */

#include  "jorte/jorte_protos_api.h"


NtpTime getNtpTime(JNIEnv *env, jobject obj)
{
  NtpTime          time;
  jfieldID         fieldID;
  jclass           ntpTimeClass;

  /* get object's class */
  ntpTimeClass = (*env)->GetObjectClass(env, obj);

  /* get object field ID - NtpTime.seconds */
  fieldID = (*env)->GetFieldID(env,ntpTimeClass,"seconds","I");
// if(fieldID == NULL) return(NTPTIME_ZERO(time)); // NEFUNGUJE
  /* get objects value */
  time.seconds = (int32_t) (*env)->GetIntField(env,obj,fieldID);

  /* reset pointer  */
  fieldID = NULL;

  /* get object field ID  - NtpTime.fraction */
  fieldID = (*env)->GetFieldID(env,ntpTimeClass,"fraction","J");
//  if(fieldID == NULL) return(NTPTIME_ZERO(time)); // NEFUNGUJE
  /* get object's value */
  time.fraction = (uint32_t) (*env)->GetIntField(env,obj,fieldID);

  return(time);

}
