/* JNtpTimeToStringMs.c */
/**
  * This code provides conversion between JAVA a C environments.
  * The C functions are calling here and results are send to JAVA
  * native functions. It uses the header pregenerated by JAVA
  * (by command 'javah -jni class_with_native_function')
  *
  * @author Lukas Pokorny (lukas_pokorny@centrum.cz)
  * @author CTU FEE Prague - Department of Control Engineering (dce.felk.cvut.cz)
  * @author Project ORTE - OCERA Real Time Ethernet (www.ocera.org)
  * @author dedication to Kj
  * @version 0.1
  *
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  */


// origin orte headers
#include "orte.h"
// pregenerated header
#include "jorte/org_ocera_orte_types_NtpTime.h"



/* native function - prototype declared in pregenerated header */
JNIEXPORT jstring JNICALL
Java_org_ocera_orte_types_JORTENtpTime_NtpTimeToStringMs
(JNIEnv *env, jclass class, jobject j_ntpTime)
{
  char             buff[65];  // 32 + 32 + 1 end char
  NtpTime          time;      
  jfieldID         fieldID;     
  jclass           ntpTimeClass;


  // NtpTime - get object's class
  ntpTimeClass = (*env)->GetObjectClass(env, j_ntpTime);

  // seconds - get object field ID
  fieldID = (*env)->GetFieldID(env,ntpTimeClass,"seconds","I");
  if(fieldID == NULL)
    return((*env)->NewStringUTF(env, "error when reading Java-ntpTime"));
  // get objects value
  time.seconds = (int32_t) (*env)->GetIntField(env,j_ntpTime,fieldID);

  // reset pointer
  fieldID = NULL;

  // fraction - get object field ID
  fieldID = (*env)->GetFieldID(env,ntpTimeClass,"fraction","J");
  if(fieldID == NULL)
    return((*env)->NewStringUTF(env, "error when reading Java-ntpTime"));
  // get object's value
  time.fraction = (uint32_t) (*env)->GetIntField(env,j_ntpTime,fieldID);

  // calling original liborte function
  NtpTimeToStringMs(time,buff);
  // return result of the conversion
  return((*env)->NewStringUTF(env, buff));
}
