/* JORTEDomainPropDefaultGet.c  */

/**
  * This code provides conversion between JAVA a C environments.
  * The C functions are calling here and results are send to JAVA
  * native functions. It uses the header pregenerated by JAVA
  * (by command 'javah -jni class_with_native_function')
  *
  * @author Lukas Pokorny (lukas_pokorny@centrum.cz)
  * @author CTU FEE Prague - Department of Control Engineering (dce.felk.cvut.cz
)
  * @author Project ORTE - OCERA Real Time Ethernet (www.ocera.org)
  * @author dedication to Kj
  * @version 0.1
  *
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  */


#include <stdlib.h>
// origin orte headers
#include "orte.h"
// pregenerated header
#include "jorte/org_ocera_orte_types_DomainProp.h"
#include "jorte/4all.h"

JNIEXPORT jint JNICALL
Java_org_ocera_orte_types_DomainProp_jORTEDomainPropDefaultGet
(JNIEnv *env, jclass cls)
{
  ORTEDomainProp *dprop;

  // memory allocation
  // don't forget use free()!!
  dprop = (ORTEDomainProp *) malloc(sizeof(ORTEDomainProp));
  if (dprop == NULL)
  {
     printf(":!c: not enough memory to alocate DomainProp!");
     return 0;
  }
  // call ORTE function
  if (!ORTEDomainPropDefaultGet(dprop))
  {
    printf(":!c: ORTEDomainPropDefaultGet() failed.. \n");
    free(dprop);
    return 0;
  }
  #ifdef TEST_STAGE
    printf(":c: default domain properties created.. \n");
  #endif
  return ((jint) dprop);
}
