/* JORTEPublicationPropertiesSet.c */

/**
  * This code provides conversion between JAVA a C environments.
  * The C functions are calling here and results are send to JAVA
  * native functions. It uses the header pregenerated by JAVA
  * (by command 'javah -jni class_with_native_function')
  *
  * @author Lukas Pokorny (lukas_pokorny@centrum.cz)
  * @author CTU FEE Prague - Department of Control Engineering (dce.felk.cvut.cz)
  * @author Project ORTE - OCERA Real Time Ethernet (www.ocera.org)
  * @author dedication to Kj
  * @version 0.1
  *
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  */

#include <string.h>
#include <stdlib.h>
// library header file's path
#include "orte.h"
// getNtpTime function
#include "jorte/jorte_protos_api.h"
// enable TEST_STAGE run level
#include "jorte/4all.h"
// pregenerated header
#include "jorte/org_ocera_orte_Publication.h"


JNIEXPORT jboolean JNICALL
Java_org_ocera_orte_Publication_jORTEPublicationPropertiesSet
(JNIEnv *env, jobject obj, jint j_appDomain_handle, jobject obj_pp)
{
  // jni types
  jclass         cls_pp = NULL;
  jfieldID       fid = NULL;
  jobject        obj_ntpT = NULL;
  jobject        obj_str = NULL;
  jboolean       jbool = 0;
  //
  int            b = 0;
  int            flag_ok = 0;
  const char    *str = NULL;
  ORTEPublProp   pp;
  ORTEPublProp  *publ_prop = &pp;

  #ifdef TEST_STAGE
    printf(":c: jORTEPublicationPropertiesSet() called.. \n");
  #endif

  do
  {
    // get 'SubProp' instance's class
    cls_pp = (*env)->GetObjectClass(env, obj_pp);
    // second way how to get 'PublProp' instance's class
    //cls_pp = (*env)->FindClass(env,"org/ocera/orte/types/PublProp");
    if(cls_pp == 0)
    {
      #ifdef TEST_STAGE
       printf(":!c: cls_pp = NULL \n");
      #endif
      break;
    }
    // ///////////////////////////////////////////////
    // setting object's fields
    /////////////////////////////////////////////////
    // set topic
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "topic",
                             "Ljava/lang/String;");
    if(fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    obj_str = (*env)->GetObjectField(env, obj_pp, fid);
    if(obj_str == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: obj_str = NULL \n");
      #endif
      break;
    }
    str = (*env)->GetStringUTFChars(env,obj_str,0);
    // set structure's field
    strncpy((char *) publ_prop->topic, str, strlen(str) + 1);
    #ifdef TEST_STAGE
      printf(":c: topic = %s, publ_prop->topic = %s \n",
             str, publ_prop->topic);
    #endif
    // free the memory
    (*env)->ReleaseStringUTFChars(env, obj_pp, str);
    /////////////////////////////////////////////////
    // set typeName
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "typeName",
                             "Ljava/lang/String;");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    obj_str = (*env)->GetObjectField(env, obj_pp, fid);
    if(obj_str == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: obj_str = NULL \n");
      #endif
      break;
    }
    str = (*env)->GetStringUTFChars(env,obj_str,0);
    // set structure's field
    strncpy((char *) publ_prop->typeName, str, strlen(str) + 1);
    #ifdef TEST_STAGE
      printf(":c: typeName = %s, publ_prop->typeName = %s \n",
             str, publ_prop->typeName);
    #endif
    // free the memory
    (*env)->ReleaseStringUTFChars(env, obj_pp, str);
    /////////////////////////////////////////////////
    // set typeChecksum
    fid = (*env)->GetFieldID(env,cls_pp,"typeChecksum","I");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    publ_prop->typeChecksum = (TypeChecksum) (*env)->GetIntField(env, obj_pp, fid);
    #ifdef TEST_STAGE
      printf(":c: check: publ_prop->typeChecksum = %d\n",
             publ_prop->typeChecksum);
    #endif
    /////////////////////////////////////////////////
    // set expectsAck
    fid = (*env)->GetFieldID(env,cls_pp,"expectsAck","Z");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    jbool = (*env)->GetBooleanField(env, obj_pp, fid);
    if (jbool == 0) publ_prop->expectsAck = ORTE_FALSE;
      else publ_prop->expectsAck = ORTE_TRUE;
    #ifdef TEST_STAGE
      printf(":c: check: publ_prop->expectsAck = %d\n", publ_prop->expectsAck);
    #endif
    /////////////////////////////////////////////////
    // set persistence
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "persistence",
                             "Lorg/ocera/orte/types/NtpTime;");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    obj_ntpT = (*env)->GetObjectField(env, obj_pp, fid);
    if (obj_ntpT == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: obj_ntpT = NULL \n");
      #endif
      break;
    }
    publ_prop->persistence = getNtpTime(env, obj_ntpT);
    #ifdef TEST_STAGE
      printf(":c: check: publ_prop->persistence: sec = %d, fract = %d  \n",
             publ_prop->persistence.seconds, publ_prop->persistence.fraction);
    #endif
    /////////////////////////////////////////////////
    // set reliabilityOffered
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "reliabilityOffered",
                             "J");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    publ_prop->reliabilityOffered = (uint32_t) (*env)->GetLongField(env, obj_pp, fid);
    #ifdef TEST_STAGE
      printf(":c: check: publ_prop->reliabilityOffered = %d \n",
             publ_prop->reliabilityOffered);
    #endif
    /////////////////////////////////////////////////
    // set sendQueueSize
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "sendQueueSize",
                             "J");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    publ_prop->sendQueueSize = (uint32_t) (*env)->GetLongField(env,obj_pp,fid);
    #ifdef TEST_STAGE
      printf(":c: check: publ_prop->sendQueueSize = %d \n",
             publ_prop->sendQueueSize);
    #endif
    /////////////////////////////////////////////////
    // set strength
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "strength",
                             "I");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    publ_prop->strength = (int32_t) (*env)->GetIntField(env,obj_pp,fid);
    #ifdef TEST_STAGE
      printf(":c: check: publ_prop->strength = %d \n",
             publ_prop->strength);
    #endif
    /////////////////////////////////////////////////
    // set criticalQueueLevel
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "criticalQueueLevel",
                             "J");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    publ_prop->criticalQueueLevel = (uint32_t) (*env)->GetLongField(env, obj_pp, fid);
    #ifdef TEST_STAGE
      printf(":c: check: publ_prop->criticalQueueLevel = %d \n",
             publ_prop->criticalQueueLevel);
    #endif
    /////////////////////////////////////////////////
    // set HBNornalRate
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "HBNornalRate",
                             "Lorg/ocera/orte/types/NtpTime;");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    obj_ntpT = (*env)->GetObjectField(env, obj_pp, fid);
    publ_prop->HBNornalRate = getNtpTime(env, obj_ntpT);
    #ifdef TEST_STAGE
    printf(":c: check: publ_prop->HBNornalRate: sec = %d, fract = %d  \n",
           publ_prop->HBNornalRate.seconds, publ_prop->HBNornalRate.fraction);
    #endif
    /////////////////////////////////////////////////
    // set HBCQLRate
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "HBCQLRate",
                             "Lorg/ocera/orte/types/NtpTime;");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    obj_ntpT = (*env)->GetObjectField(env, obj_pp, fid);
    if (obj_ntpT == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: obj_ntpT = NULL \n");
      #endif
      break;
    }
    publ_prop->HBCQLRate = getNtpTime(env, obj_ntpT);
    #ifdef TEST_STAGE
      printf(":c: check: publ_prop->HBCQLRate: sec = %d, fract = %d  \n",
             publ_prop->HBCQLRate.seconds, publ_prop->HBCQLRate.fraction);
    #endif
    /////////////////////////////////////////////////
    // set HBMaxRetries
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "HBMaxRetries",
                             "J");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    publ_prop->HBMaxRetries = (unsigned int) (*env)->GetLongField(env, obj_pp, fid);
    #ifdef TEST_STAGE
      printf(":c: check: publ_prop->HBMaxRetries = %d \n",
             publ_prop->HBMaxRetries);
    #endif
    /////////////////////////////////////////////////
    // set maxBlockTime
    fid = (*env)->GetFieldID(env,
                             cls_pp,
                             "maxBlockTime",
                             "Lorg/ocera/orte/types/NtpTime;");
    if (fid == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: fid = NULL \n");
      #endif
      break;
    }
    obj_ntpT = (*env)->GetObjectField(env, obj_pp, fid);
    if (obj_ntpT == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: obj_ntpT = NULL \n");
      #endif
      break;
    }
    publ_prop->maxBlockTime = getNtpTime(env, obj_ntpT);
    #ifdef TEST_STAGE
      printf(":c: check: publ_prop->maxBlockTime: sec = %d, fract = %d  \n",
             publ_prop->maxBlockTime.seconds, publ_prop->maxBlockTime.fraction);
    #endif
    /////////////////////////////////////////////////
    // calling original native method
    b = ORTEPublicationPropertiesSet((ORTEPublication *) j_appDomain_handle,
                                     publ_prop);
    if (b == ORTE_BAD_HANDLE)
    {
      printf(":c!: set pub properties failed! [bad pub handle] \n");
      break;
    }
    // set flag
    flag_ok = 1;
  } while(0);

  if(flag_ok == 0)
  {
    return 0;
  }

  return 1;

}
