/* JORTEDomainPropDefaultGet.c  */

/**
  * This code provides conversion between JAVA a C environments.
  * The C functions are calling here and results are send to JAVA
  * native functions. It uses the header pregenerated by JAVA
  * (by command 'javah -jni class_with_native_function')
  *
  * @author Lukas Pokorny (lukas_pokorny@centrum.cz)
  * @author CTU FEE Prague - Department of Control Engineering (dce.felk.cvut.cz
)
  * @author Project ORTE - OCERA Real Time Ethernet (www.ocera.org)
  * @author dedication to Kj
  * @version 0.1
  *
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  */


#include <stdlib.h>
// origin orte headers
#include "orte.h"
// pregenerated header
#include "jorte/org_ocera_orte_DomainProp.h"



JNIEXPORT jint JNICALL
Java_org_ocera_orte_DomainProp_jORTEDomainPropDefaultGet
(JNIEnv *env, jclass cls)
{
  ORTEDomainProp *dprop;

  /* allocation space for the pointer to struc ORTEDomainProp  */
  dprop = (ORTEDomainProp *) malloc(sizeof(ORTEDomainProp));
  if (dprop == NULL) {
     printf(":!c: not enough of memory to alocation ORTEDomainProp..");
     return 0;
  }

  /* call the liborte function */
  if (!ORTEDomainPropDefaultGet(dprop)) {
    printf(":!c: ORTEDomainPropDefaultGet() failed.. \n");
    free(dprop);
    return 0;
  }
  printf(":c: ORTEDomainPropDefaultGet() succesful.. %p \n",dprop);
  return ((jint) dprop);

}
