/* JORTESubscriptionDestroy.c */

/**
  * This code provides conversion between JAVA a C environments.
  * The C functions are calling here and results are send to JAVA
  * native functions. It uses the header pregenerated by JAVA
  * (by command 'javah -jni class_with_native_function')
  *
  * @author Lukas Pokorny (lukas_pokorny@centrum.cz)
  * @author CTU FEE Prague - Department of Control Engineering (dce.felk.cvut.cz)
  * @author Project ORTE - OCERA Real Time Ethernet (www.ocera.org)
  * @author dedication to Kj
  * @version 0.1
  *
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  */


#include <stdlib.h>
// library header file's path
#include "orte.h"
// enable TEST_STAGE run level
#include "jorte/4all.h"
// pregenerated header
#include "jorte/org_ocera_orte_Subscription.h"
//
#include "jorte/typedefs_defines_jorte.h"

JNIEXPORT jboolean JNICALL
Java_org_ocera_orte_Subscription_jORTESubscriptionDestroy
(JNIEnv *env, jobject obj, jint dhandle)
{
  int8_t        b;
  jint          h;
  jclass        cls;
  jfieldID      fid;

  printf(":!c: ORTESubscriptionDestroy() called.. \n");
  // free callBack object
  cls = (*env)->GetObjectClass(env, obj);
  fid = (*env)->GetFieldID(env, cls, "callbackContextHandle", "I");
  h   = (*env)->GetIntField(env, obj, fid);
  //(*env)->SetIntField(env, obj, fid, 0);
  printf(":!c: JORTECallbackContext_t handle: %x\n", h);
  if(h) {
	//JavaVM *jvm;
    //jint ret;
    printf(":c: ORTESubscriptionDestroy() destroying JORTECallbackContext_t.. \n");
	JORTECallbackContext_t *ctx = (JORTECallbackContext_t*)h;
    if(ctx->obj) {
        printf(":!c: deleting ctx->obj\n");
	    (*env)->DeleteLocalRef(env, ctx->obj);
	}
    if(ctx->rinfo) {
        printf(":!c: deleting ctx->rinfo\n");
	    (*env)->DeleteLocalRef(env, ctx->rinfo);
	}

    free((void*)h);
  }
  // call the liborte destroy function
  printf(":!c: ORTESubscription handle: %x\n", dhandle);
  if(dhandle) {
	b = ORTESubscriptionDestroy((ORTESubscription *) dhandle);
	if(b == ORTE_OK)
	{
		printf(":c: ORTESubscriptionDestroy() succesfuly.. \n");
		return 1;
	}
	if (b == ORTE_BAD_HANDLE)
		printf(":!c: ORTESubscriptionDestroy() failed! (bad subsriber's handle) \n");
  }
  return 0;
}

