/* JORTEPublicationSend.c */

/**
  * This code provides conversion between JAVA a C environments.
  * The C functions are calling here and results are send to JAVA
  * native functions. It uses the header pregenerated by JAVA
  * (by command 'javah -jni class_with_native_function')
  *
  * @author Lukas Pokorny (lukas_pokorny@centrum.cz)
  * @author CTU FEE Prague - Department of Control Engineering (dce.felk.cvut.cz)
  * @author Project ORTE - OCERA Real Time Ethernet (www.ocera.org)
  * @author dedication to Kj
  * @version 0.1
  *
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  */


#include <stdlib.h>
// library header file's path
#include "orte.h"
// pregenerated header
#include "jorte/org_ocera_orte_Publication.h"
// enable TEST_STAGE run level
#include "jorte/4all.h"


JNIEXPORT jboolean JNICALL
Java_org_ocera_orte_Publication_jORTEPublicationSend
  (JNIEnv *env, jobject obj, jlong pub_handle)
{
  int       flag_ok = 0;
  int8_t    b;

  //

  #ifdef TEST_STAGE
  printf(":c: jORTEPublicationSend() called.. \n");
  #endif

  do {
    /////////////////////////////////////////////////
    // call ORTE function
    b = ORTEPublicationSend((ORTEPublication *)pub_handle);
    #ifdef TEST_STAGE
    printf(":c: b = ORTEPublicationSend() = %d \n", b);
    #endif
    if (b == ORTE_BAD_HANDLE) {
     #ifdef TEST_STAGE
      printf(":!c: data not sent! [bad pub handle] \n");
     #endif
      break;
    }
    if (b == ORTE_OK) {
     #ifdef TEST_STAGE
      printf(":c: data sent succesfuly.. \n");
     #endif
    }
    // set flag
    flag_ok = 1;
  } while (0);

  if (flag_ok == 0) {
    return 0;
  }

  return 1;

}
