/* JORTEPublicationCreate.c */

/**
  * This code provides conversion between JAVA a C environments.
  * The C functions are calling here and results are send to JAVA
  * native functions. It uses the header pregenerated by JAVA
  * (by command 'javah -jni class_with_native_function')
  *
  * @author Lukas Pokorny (lukas_pokorny@centrum.cz)
  * @author CTU FEE Prague - Department of Control Engineering (dce.felk.cvut.cz)
  * @author Project ORTE - OCERA Real Time Ethernet (www.ocera.org)
  * @author dedication to Kj
  * @version 0.1
  *
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  */


#include <stdlib.h>
#include  "jorte/getNtpTime.h"
// origin orte headers
#include "orte.h"
// pregenerated header
#include "jorte/org_ocera_orte_Publication.h"



// ### DOCASNE ##################################################################


// ### DOCASNE ##################################################################
int counter = 0;

void
sendCallBack(const ORTESendInfo *info,void *vinstance, void *sendCallBackParam) {
  char *instance=(char*)vinstance;

  printf(":c: zacatek sendCallBack()..\n");

  switch (info->status) {
    case NEED_DATA:
      printf(":c:PUB: Sampling publication, count %d\n", counter);
      printf(":c:PUB: !! DOCASNE - ZRUSIT!! - callback() u Publishera \n");
	  sprintf(instance,"Hello Universe! (%d)",counter++);
      break;
    case CQL:  //criticalQueueLevel
      break;
  }
}

// ### DOCASNE ##################################################################

// ### DOCASNE ##################################################################


JNIEXPORT jint JNICALL
Java_org_ocera_orte_Publication_jORTEPublicationCreate
(JNIEnv *env , jobject obj, jint dom_handle, jstring j_topic,
 jstring j_type_name, jobject j_instance, jobject j_persistence,
 jint j_strength /*, callback not used */)
{
  ORTEPublication  *p;
  ORTEDomain       *d;
  const char       *topic;
  const char       *typename;
  char             *buffer;  // dynamicky naalokovat pole instance2send @!!!!!!!!!!!!
  NtpTime           persistence;
  int               strength;
  jclass            cls;
  jmethodID         mid;
  jint              buff_length;

  printf(":c: chystam se vytvorit publikaci\n");
  d = (ORTEDomain *) dom_handle;
  if (!d) {
    printf(":!c: jORTEPublicationCreate() fault - bad domain handle! \n ");
    return 0;
  }

  topic = (*env)->GetStringUTFChars(env, j_topic, 0);
  typename = (*env)->GetStringUTFChars(env, j_type_name, 0);



  persistence = getNtpTime(env, j_persistence);
  strength = (int) j_strength;


  printf(":c: jORTEPublicationCreate() - nacteny parametry z javy..\n");


  // create buffer

  // get object's class
  cls = (*env)->GetObjectClass(env, j_instance);
  if(!cls)
  {
    printf(":!c: Class of 'instance' not found! \n");
    return 0;
  }
  // get method ID
  mid = (*env)->GetMethodID(env, cls, "getMaxSerializeLength", "()I");
  if(!mid)
  {
    printf(":!c: Method getMaxSerializeLength() not found! \n");
    return 0; // ma se pri selhani RecvInfa davat tvrdy return?
  }

/*
  // get fieldID
  if((fieldID = (*env)->GetFieldID(env,cls_instance,"seconds","I")) == NULL)
    return((*env)->NewStringUTF(env, "error when reading Java-ntpTime"));
  // get objects value
  time.seconds = (int32_t) (*env)->GetIntField(env,j_ntpTime,fieldID);
*/




  // get class MessageData
  cls = (*env)->GetObjectClass(env, j_instance);
  if(cls == 0)
  {
    printf(":!c: cannot find MessageData class! \n");
    return 0;
  }
  // get class's method ID
  mid = (*env)->GetMethodID(env,
                            cls,
                            "getMaxSerializeLength",
                            "()I");
  if(mid == 0)
  {
    printf(":!c: method getMaxSerializeLength failed! \n");
    return 0;
  }
  // calling method
  buff_length = (*env)->CallIntMethod(env,
                                 j_instance,
                                 mid);

  buffer = (char*) malloc((int) buff_length); // 64 !!! provizorne - upravit!!


  /* call original ORTE function */
  p = ORTEPublicationCreate(d,
                            topic,
							typename,
							(void *) buffer,
							&persistence,
                            strength,
							sendCallBack, /* BUDE NULL !!!*/
							j_instance,
							NULL);

  printf(":c: provedeno volani ORTEPublicationCreate() \n");

  if (!p) {
    printf(":!c: jORTEPublicationCreate() fault! (bad publication handle).. \n ");
    return 0;
  }


  /* free the memory */
  (*env)->ReleaseStringUTFChars(env, j_topic, topic);
  (*env)->ReleaseStringUTFChars(env, j_type_name, typename);
  /* free the alocated memory  - buffer !!!!*/

  return ((jint) p);
}

