/* JORTEDomainMgrDestroy.c  */

/**
  * This code provides conversion between JAVA a C environments.
  * The C functions are calling here and results are send to JAVA
  * native functions. It uses the header pregenerated by JAVA
  * (by command 'javah -jni class_with_native_function')
  *
  * @author Lukas Pokorny (lukas_pokorny@centrum.cz)
  * @author Martin Vajnar (martin.vajnar@gmail.com)
  * @author CTU FEE Prague - Department of Control Engineering (dce.felk.cvut.cz)
  * @author Project ORTE - OCERA Real Time Ethernet (www.ocera.org)
  * @author dedication to Kj
  * @version 0.1
  *
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  */

#include "jorte/jorte.h"

JNIEXPORT jboolean JNICALL
Java_org_ocera_orte_DomainMgr_jORTEDomainMgrDestroy
(JNIEnv *env, jobject obj, jlong dhandle)
{
  jlong       h;
  jclass      cls;
  jfieldID    fid;
  int         flag_ok = 0;

  do {
    // check domain handle
    if (dhandle == 0)
    {
      printf(":!c: ORTEDomainAppDestroy failed! [bad handle] \n");
      break;
    }
    // call ORTE function
    if(!ORTEDomainMgrDestroy((ORTEDomain *) dhandle))
    {
      #ifdef TEST_STAGE
        printf(":c: mgrDomain destroy failed.. \n");
      #endif
      break;
    }
    // free domainEvents object
    // find cls
    cls = (*env)->GetObjectClass(env, obj);
    if(cls == 0)
    {
      #ifdef TEST_STAGE
        printf(":!c: cls = NULL! \n");
      #endif
      break;
    }
    // fieldID
    fid = (*env)->GetFieldID(env,
                             cls,
                             "domainEventsContextHandle",
                             "J");
    if(fid == 0)
    {
     #ifdef TEST_STAGE
       printf(":!c: fid = NULL! \n");
     #endif
     break;
    }
    // get value
    h = (*env)->GetLongField(env, obj, fid);
    if(h)
    {
      JORTEDomainEventsContext_t *ctx = (JORTEDomainEventsContext_t*)h;
      if(ctx->obj_de)
      {
        #ifdef TEST_STAGE
          printf(":c: deleting ctx->obj_de \n");
        #endif
        (*env)->DeleteGlobalRef(env, ctx->obj_de);
      }
      //
      free((void*)h);
    }
    flag_ok = 1;
  } while(0);

  if(flag_ok == 0)
  {
    printf(":!c: ORTEDomainMgrDestroy failed!  \n");
    return 0;
  }

  return 1;
}
