/**
  * This code provides conversion between JAVA a C environments.
  * The C functions are calling here and results are send to JAVA
  * native functions. It uses the header pregenerated by JAVA
  * (by command 'javah -jni class_with_native_function')
  *
  * @author Lukas Pokorny (lukas_pokorny@centrum.cz)
  * @author Martin Vajnar (martin.vajnar@gmail.com)
  * @author CTU FEE Prague - Department of Control Engineering (dce.felk.cvut.cz)
  * @author Project ORTE - OCERA Real Time Ethernet (www.ocera.org)
  * @author dedication to Kj
  * @version 0.1
  *
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation; either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  */

#include "jorte/jorte.h"

static jmethodID findClassM;
static jmethodID findLoadedClassM;
static jobject classLoader;

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *reserved) {
  JNIEnv *env;
  jclass testCl;
  jclass clClass;
  jclass clClassLoader;
  jmethodID getClassLoader;

  (*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_6);

  testCl = (*env)->FindClass(env, "org/ocera/orte/JOrte");
  clClass = (*env)->FindClass(env, "java/lang/Class");
  clClassLoader = (*env)->FindClass(env, "java/lang/ClassLoader");
  getClassLoader = (*env)->GetMethodID(env, clClass, "getClassLoader", "()Ljava/lang/ClassLoader;");
  classLoader = (*env)->CallObjectMethod(env, testCl, getClassLoader);
  classLoader = (*env)->NewGlobalRef(env, classLoader);
  findClassM = (*env)->GetMethodID(env, clClassLoader, "findClass", "(Ljava/lang/String;)Ljava/lang/Class;");
  findLoadedClassM = (*env)->GetMethodID(env, clClassLoader, "findLoadedClass", "(Ljava/lang/String;)Ljava/lang/Class;");

  return JNI_VERSION_1_6;
}

JNIEXPORT void JNICALL JNI_OnUnload(JavaVM *vm, void *reserved) {
  JNIEnv *env;

  (*vm)->GetEnv(vm, (void **)&env, JNI_VERSION_1_6);

  (*env)->DeleteGlobalRef(env, classLoader);
}

jclass findClass(JNIEnv *env, const char* name) {
  jclass cl;

  if ((cl = (*env)->CallObjectMethod(env, classLoader, findLoadedClassM, (*env)->NewStringUTF(env, name))) == NULL) {
    cl = (*env)->CallObjectMethod(env, classLoader, findClassM, (*env)->NewStringUTF(env, name));
  }

  return cl;
}
