/*
 * This file was generated by orte-idl - DO NOT EDIT!
 */

#include "BoxType.h"

/****************************************************************/
/* struct - BoxRect                                             */
/****************************************************************/

void BoxRect_serialize(CDR_Codec *cdrCodec,BoxRect *object) {
  CORBA_short_serialize(cdrCodec,&(object->top_left_x));
  CORBA_short_serialize(cdrCodec,&(object->top_left_y));
  CORBA_short_serialize(cdrCodec,&(object->bottom_right_x));
  CORBA_short_serialize(cdrCodec,&(object->bottom_right_y));
}

void
BoxRect_deserialize(CDR_Codec *cdrCodec,BoxRect *object) {
  CORBA_short_deserialize(cdrCodec,&(object->top_left_x));
  CORBA_short_deserialize(cdrCodec,&(object->top_left_y));
  CORBA_short_deserialize(cdrCodec,&(object->bottom_right_x));
  CORBA_short_deserialize(cdrCodec,&(object->bottom_right_y));
}

int
BoxRect_get_max_size(ORTEGetMaxSizeParam *gms) {
  CORBA_short_get_max_size(gms);
  CORBA_short_get_max_size(gms);
  CORBA_short_get_max_size(gms);
  CORBA_short_get_max_size(gms);
  return gms->csize;
}

Boolean
BoxRect_type_register(ORTEDomain *d) {
  Boolean ret;

  ret=ORTETypeRegisterAdd(d,
                          "BoxRect",
                          (ORTETypeSerialize)BoxRect_serialize,
                          (ORTETypeDeserialize)BoxRect_deserialize,
                          BoxRect_get_max_size,
                          0);
  return ret;
}

/****************************************************************/
/* struct - BoxType                                             */
/****************************************************************/

void BoxType_serialize(CDR_Codec *cdrCodec,BoxType *object) {
  CORBA_octet_serialize(cdrCodec,&(object->color));
  CORBA_long_serialize(cdrCodec,&(object->shape));
  BoxRect_serialize(cdrCodec,&(object->rectangle));
}

void
BoxType_deserialize(CDR_Codec *cdrCodec,BoxType *object) {
  CORBA_octet_deserialize(cdrCodec,&(object->color));
  CORBA_long_deserialize(cdrCodec,&(object->shape));
  BoxRect_deserialize(cdrCodec,&(object->rectangle));
}

int
BoxType_get_max_size(ORTEGetMaxSizeParam *gms) {
  CORBA_octet_get_max_size(gms);
  CORBA_long_get_max_size(gms);
  BoxRect_get_max_size(gms);
  return gms->csize;
}

Boolean
BoxType_type_register(ORTEDomain *d) {
  Boolean ret;

  ret=ORTETypeRegisterAdd(d,
                          "BoxType",
                          (ORTETypeSerialize)BoxType_serialize,
                          (ORTETypeDeserialize)BoxType_deserialize,
                          BoxType_get_max_size,
                          0);
  return ret;
}

