ifeq ($(CONFIG_OC_ETH_ORTE_EXAMPLES),y)

utils_PROGRAMS = m_subscriber

INCLUDES = -I $(srcdir)/../../include

m_subscriber_SOURCES = m_subscriber.c

lib_LOADLIBES =  orte pthread

endif #CONFIG_OC_ETH_ORTE_EXAMPLES

