ifeq ($(CONFIG_OC_ETH_ORTE_EXAMPLES),y)

ifeq ($(CONFIG_OC_ETH_ORTE_EXAMPLES_AS_LIBRARY),y)
INCLUDES += -D MAIN_RENAMED
lib_LIBRARIES = ortespy
else
bin_PROGRAMS = ortespy
endif

ortespy_SOURCES = ortespy.c

lib_LOADLIBES =  orte pthread
ifeq ($(TARGET_OS),win32)
lib_LOADLIBES +=  ws2_32
endif #TARGET_OS

endif #CONFIG_OC_ETH_ORTE_EXAMPLES
