ifeq ($(CONFIG_OC_ETH_ORTE_EXAMPLES),y)

utils_PROGRAMS = r_publisher r_subscriber_reliable r_subscriber_besteffort

r_publisher_SOURCES = r_publisher.c

r_subscriber_reliable_SOURCES = r_subscriber_reliable.c

r_subscriber_besteffort_SOURCES = r_subscriber_besteffort.c

lib_LOADLIBES =  orte pthread
ifeq ($(TARGET_OS),win32)
lib_LOADLIBES +=  ws2_32
endif #TARGET_OS

endif #CONFIG_OC_ETH_ORTE_EXAMPLES
