/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_Publication */

#ifndef _Included_org_ocera_orte_Publication
#define _Included_org_ocera_orte_Publication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_Publication
 * Method:    jORTEPublicationCreate
 * Signature: (ILjava/lang/String;Ljava/lang/String;Lorg/ocera/orte/types/MessageData;Lorg/ocera/orte/types/NtpTime;I)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_Publication_jORTEPublicationCreate
  (JNIEnv *, jobject, jint, jstring, jstring, jobject, jobject, jint);

/*
 * Class:     org_ocera_orte_Publication
 * Method:    jORTEPublicationDestroy
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_Publication_jORTEPublicationDestroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ocera_orte_Publication
 * Method:    jORTEPublicationSend
 * Signature: (ILorg/ocera/orte/types/MessageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_Publication_jORTEPublicationSend
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
