/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_types_RecvInfo */

#ifndef _Included_org_ocera_orte_types_RecvInfo
#define _Included_org_ocera_orte_types_RecvInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_types_RecvInfo
 * Method:    get_ORTERecvInfo_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_types_RecvInfo_get_1ORTERecvInfo_1size
  (JNIEnv *, jobject);

/*
 * Class:     org_ocera_orte_types_RecvInfo
 * Method:    get_ORTERecvStatus_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_types_RecvInfo_get_1ORTERecvStatus_1size
  (JNIEnv *, jobject);

/*
 * Class:     org_ocera_orte_types_RecvInfo
 * Method:    get_char_ptr_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_types_RecvInfo_get_1char_1ptr_1size
  (JNIEnv *, jobject);

/*
 * Class:     org_ocera_orte_types_RecvInfo
 * Method:    get_string
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ocera_orte_types_RecvInfo_get_1string
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
