/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_types_DomainEvents */

#ifndef _Included_org_ocera_orte_types_DomainEvents
#define _Included_org_ocera_orte_types_DomainEvents
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_types_DomainEvents
 * Method:    jORTEDomainInitEvents
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL
Java_org_ocera_orte_types_DomainEvents_jORTEDomainInitEvents
  (JNIEnv *, jobject);

/*
 * Class:     org_ocera_orte_types_DomainEvents
 * Method:    jORTEDomainEventsDestroy
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL
Java_org_ocera_orte_types_DomainEvents_jORTEDomainEventsDestroy
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
