/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_types_DomainProp */

#ifndef _Included_org_ocera_orte_types_DomainProp
#define _Included_org_ocera_orte_types_DomainProp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_types_DomainProp
 * Method:    jORTEDomainPropDefaultGet
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_ocera_orte_types_DomainProp_jORTEDomainPropDefaultGet
  (JNIEnv *, jclass);

/*
 * Class:     org_ocera_orte_types_DomainProp
 * Method:    jORTEDomainPropSet
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_types_DomainProp_jORTEDomainPropSet
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_ocera_orte_types_DomainProp
 * Method:    jORTEDomainPropDestroy
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_types_DomainProp_jORTEDomainPropDestroy
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
