/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_types_DomainProp */

#ifndef _Included_org_ocera_orte_types_DomainProp
#define _Included_org_ocera_orte_types_DomainProp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_types_DomainProp
 * Method:    jORTEDomainPropDefaultGet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_types_DomainProp_jORTEDomainPropDefaultGet
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
