/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_DomainMgr */

#ifndef _Included_org_ocera_orte_DomainMgr
#define _Included_org_ocera_orte_DomainMgr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_DomainMgr
 * Method:    jORTEDomainDefaultMgrCreate
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_DomainMgr_jORTEDomainDefaultMgrCreate
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_ocera_orte_DomainMgr
 * Method:    jORTEDomainMgrCreate
 * Signature: (IIIZ)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_DomainMgr_jORTEDomainMgrCreate
  (JNIEnv *, jclass, jint, jint, jint, jboolean);

/*
 * Class:     org_ocera_orte_DomainMgr
 * Method:    jORTEDomainMgrDestroy
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_DomainMgr_jORTEDomainMgrDestroy
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
