/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_JOrte */

#ifndef _Included_org_ocera_orte_JOrte
#define _Included_org_ocera_orte_JOrte
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_JOrte
 * Method:    jORTEInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ocera_orte_JOrte_jORTEInit
  (JNIEnv *, jclass);

/*
 * Class:     org_ocera_orte_JOrte
 * Method:    jORTESleepMs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ocera_orte_JOrte_jORTESleepMs
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ocera_orte_JOrte
 * Method:    jORTEVerbositySetOptions
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ocera_orte_JOrte_jORTEVerbositySetOptions
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_ocera_orte_JOrte
 * Method:    jORTEVerbositySetLogFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ocera_orte_JOrte_jORTEVerbositySetLogFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_ocera_orte_JOrte
 * Method:    jORTEAppSendThread
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_ocera_orte_JOrte_jORTEAppSendThread
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
