/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_types_NtpTime */

#ifndef _Included_org_ocera_orte_types_NtpTime
#define _Included_org_ocera_orte_types_NtpTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_types_NtpTime
 * Method:    NtpTimeToStringMs
 * Signature: (Lorg/ocera/orte/types/NtpTime;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ocera_orte_types_NtpTime_NtpTimeToStringMs
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_ocera_orte_types_NtpTime
 * Method:    NtpTimeToStringUs
 * Signature: (Lorg/ocera/orte/types/NtpTime;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ocera_orte_types_NtpTime_NtpTimeToStringUs
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
