/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_tools_GetORTEConstant */

#ifndef _Included_org_ocera_orte_tools_GetORTEConstant
#define _Included_org_ocera_orte_tools_GetORTEConstant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_tools_GetORTEConstant
 * Method:    getConstant
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_tools_GetORTEConstant_getConstant
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
