/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_Domain */

#ifndef _Included_org_ocera_orte_Domain
#define _Included_org_ocera_orte_Domain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_Domain
 * Method:    jORTEDomainStart
 * Signature: (IZZZ)V
 */
JNIEXPORT void JNICALL Java_org_ocera_orte_Domain_jORTEDomainStart
  (JNIEnv *, jclass, jint, jboolean, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
