/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_Domain */

#ifndef _Included_org_ocera_orte_Domain
#define _Included_org_ocera_orte_Domain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_Domain
 * Method:    jORTEDomainDefaultAppCreate
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_Domain_jORTEDomainDefaultAppCreate
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_ocera_orte_Domain
 * Method:    jORTEDomainAppCreate
 * Signature: (IIIZ)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_Domain_jORTEDomainAppCreate
  (JNIEnv *, jclass, jint, jint, jint, jboolean);

/*
 * Class:     org_ocera_orte_Domain
 * Method:    jORTEDomainADestroy
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_Domain_jORTEDomainADestroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ocera_orte_Domain
 * Method:    jORTEDomainStart
 * Signature: (IZZZ)V
 */
JNIEXPORT void JNICALL Java_org_ocera_orte_Domain_jORTEDomainStart
  (JNIEnv *, jclass, jint, jboolean, jboolean, jboolean);

/*
 * Class:     org_ocera_orte_Domain
 * Method:    jORTETypeRegisterAdd
 * Signature: (ILjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_Domain_jORTETypeRegisterAdd
  (JNIEnv *, jclass, jint, jstring, jlong);

/*
 * Class:     org_ocera_orte_Domain
 * Method:    jORTETypeRegisterDestroyAll
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_Domain_jORTETypeRegisterDestroyAll
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
