/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_types_DomainEvents */

#ifndef _Included_org_ocera_orte_types_DomainEvents
#define _Included_org_ocera_orte_types_DomainEvents
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_types_DomainEvents
 * Method:    jORTEDomainInitEvents
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_types_DomainEvents_jORTEDomainInitEvents
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
