/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_DomainApp */

#ifndef _Included_org_ocera_orte_DomainApp
#define _Included_org_ocera_orte_DomainApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_DomainApp
 * Method:    jORTEDomainDefaultAppCreate
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_DomainApp_jORTEDomainDefaultAppCreate
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_ocera_orte_DomainApp
 * Method:    jORTEDomainAppCreate
 * Signature: (IIILorg/ocera/orte/types/DomainEvents;Z)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_DomainApp_jORTEDomainAppCreate
  (JNIEnv *, jclass, jint, jint, jint, jobject, jboolean);

/*
 * Class:     org_ocera_orte_DomainApp
 * Method:    jORTEDomainAppDestroy
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_DomainApp_jORTEDomainAppDestroy
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_ocera_orte_DomainApp
 * Method:    jORTETypeRegisterAdd
 * Signature: (ILjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_DomainApp_jORTETypeRegisterAdd
  (JNIEnv *, jclass, jint, jstring, jlong);

/*
 * Class:     org_ocera_orte_DomainApp
 * Method:    jORTETypeRegisterDestroyAll
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_DomainApp_jORTETypeRegisterDestroyAll
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
