/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_tools_Conversions */

#ifndef _Included_org_ocera_orte_tools_Conversions
#define _Included_org_ocera_orte_tools_Conversions
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_tools_Conversions
 * Method:    IPAddressToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ocera_orte_tools_Conversions_IPAddressToString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ocera_orte_tools_Conversions
 * Method:    StringToIPAddress
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_ocera_orte_tools_Conversions_StringToIPAddress
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
