/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_Subscription */

#ifndef _Included_org_ocera_orte_Subscription
#define _Included_org_ocera_orte_Subscription
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_Subscription
 * Method:    jORTESubscriptionCreate
 * Signature: (IIILjava/lang/String;Ljava/lang/String;ILorg/ocera/orte/types/NtpTime;Lorg/ocera/orte/types/NtpTime;Lorg/ocera/orte/SubscriptionCallback;J)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_Subscription_jORTESubscriptionCreate
  (JNIEnv *, jobject, jint, jint, jint, jstring, jstring, jint, jobject, jobject, jobject, jlong);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    jORTESubscriptionDestroy
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_Subscription_jORTESubscriptionDestroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    getTopic
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ocera_orte_Subscription_getTopic
  (JNIEnv *, jclass);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    getTypeName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ocera_orte_Subscription_getTypeName
  (JNIEnv *, jclass);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    getDeadline
 * Signature: ()Lorg/ocera/orte/types/NtpTime;
 */
JNIEXPORT jobject JNICALL Java_org_ocera_orte_Subscription_getDeadline
  (JNIEnv *, jclass);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    getMinSeparation
 * Signature: ()Lorg/ocera/orte/types/NtpTime;
 */
JNIEXPORT jobject JNICALL Java_org_ocera_orte_Subscription_getMinSeparation
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
