/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_Publication */

#ifndef _Included_org_ocera_orte_Publication
#define _Included_org_ocera_orte_Publication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_Publication
 * Method:    jORTEPublicationCreate
 * Signature: (ILjava/lang/String;Ljava/lang/String;ILjava/nio/ByteBuffer;Lorg/ocera/orte/types/NtpTime;I)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_Publication_jORTEPublicationCreate
  (JNIEnv *, jobject, jint, jstring, jstring, jint, jobject, jobject, jint);

/*
 * Class:     org_ocera_orte_Publication
 * Method:    jORTEPublicationDestroy
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_Publication_jORTEPublicationDestroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ocera_orte_Publication
 * Method:    jORTEPublicationSend
 * Signature: (ILorg/ocera/orte/types/MessageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_Publication_jORTEPublicationSend
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_ocera_orte_Publication
 * Method:    jORTEPublicationPropertiesGet
 * Signature: (I)Lorg/ocera/orte/types/PublProp;
 */
JNIEXPORT jobject JNICALL Java_org_ocera_orte_Publication_jORTEPublicationPropertiesGet
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ocera_orte_Publication
 * Method:    jORTEPublicationPropertiesSet
 * Signature: (ILorg/ocera/orte/types/PublProp;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_Publication_jORTEPublicationPropertiesSet
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_ocera_orte_Publication
 * Method:    jORTEPublicationGetStatus
 * Signature: (I)Lorg/ocera/orte/types/Status;
 */
JNIEXPORT jobject JNICALL Java_org_ocera_orte_Publication_jORTEPublicationGetStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ocera_orte_Publication
 * Method:    jORTEPublicationWaitForSubscriptions
 * Signature: (ILorg/ocera/orte/types/NtpTime;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_Publication_jORTEPublicationWaitForSubscriptions
  (JNIEnv *, jobject, jint, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
