/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_DomainMgr */

#ifndef _Included_org_ocera_orte_DomainMgr
#define _Included_org_ocera_orte_DomainMgr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_DomainMgr
 * Method:    jORTEDomainDefaultMgrCreate
 * Signature: (IZ)J
 */
JNIEXPORT jlong JNICALL Java_org_ocera_orte_DomainMgr_jORTEDomainDefaultMgrCreate
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     org_ocera_orte_DomainMgr
 * Method:    jORTEDomainMgrCreate
 * Signature: (IJJZ)J
 */
JNIEXPORT jlong JNICALL Java_org_ocera_orte_DomainMgr_jORTEDomainMgrCreate
  (JNIEnv *, jclass, jint, jlong, jlong, jboolean);

/*
 * Class:     org_ocera_orte_DomainMgr
 * Method:    jORTEDomainMgrDestroy
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_DomainMgr_jORTEDomainMgrDestroy
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
