/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_DomainApp */

#ifndef _Included_org_ocera_orte_DomainApp
#define _Included_org_ocera_orte_DomainApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_DomainApp
 * Method:    jORTEDomainDefaultAppCreate
 * Signature: (IZ)J
 */
JNIEXPORT jlong JNICALL Java_org_ocera_orte_DomainApp_jORTEDomainDefaultAppCreate
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_ocera_orte_DomainApp
 * Method:    jORTEDomainAppCreate
 * Signature: (IJJLorg/ocera/orte/types/DomainEvents;Z)J
 */
JNIEXPORT jlong JNICALL Java_org_ocera_orte_DomainApp_jORTEDomainAppCreate
  (JNIEnv *, jobject, jint, jlong, jlong, jobject, jboolean);

/*
 * Class:     org_ocera_orte_DomainApp
 * Method:    jORTEDomainAppDestroy
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_DomainApp_jORTEDomainAppDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ocera_orte_DomainApp
 * Method:    jORTETypeRegisterAdd
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_DomainApp_jORTETypeRegisterAdd
  (JNIEnv *, jobject, jlong, jstring, jlong, jobject);

/*
 * Class:     org_ocera_orte_DomainApp
 * Method:    jORTETypeRegisterDestroyAll
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_DomainApp_jORTETypeRegisterDestroyAll
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
