/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_types_RecvInfo */

#ifndef _Included_org_ocera_orte_types_RecvInfo
#define _Included_org_ocera_orte_types_RecvInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_types_RecvInfo
 * Method:    get_string
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ocera_orte_types_RecvInfo_get_1string
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_ocera_orte_types_RecvInfo
 * Method:    c_helper
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_ocera_orte_types_RecvInfo_c_1helper
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
