/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ocera_orte_Subscription */

#ifndef _Included_org_ocera_orte_Subscription
#define _Included_org_ocera_orte_Subscription
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ocera_orte_Subscription
 * Method:    jORTESubscriptionCreate
 * Signature: (IIILjava/lang/String;Ljava/lang/String;ILorg/ocera/orte/types/MessageData;Lorg/ocera/orte/types/NtpTime;Lorg/ocera/orte/types/NtpTime;Lorg/ocera/orte/SubscriptionCallback;J)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_Subscription_jORTESubscriptionCreate
  (JNIEnv *, jobject, jint, jint, jint, jstring, jstring, jint, jobject, jobject, jobject, jobject, jlong);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    jORTESubscriptionDestroy
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_Subscription_jORTESubscriptionDestroy
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    jORTESubscriptionPropertiesGet
 * Signature: (I)Lorg/ocera/orte/types/SubsProp;
 */
JNIEXPORT jobject JNICALL Java_org_ocera_orte_Subscription_jORTESubscriptionPropertiesGet
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    jORTESubscriptionPropertiesSet
 * Signature: (ILorg/ocera/orte/types/SubsProp;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ocera_orte_Subscription_jORTESubscriptionPropertiesSet
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    jORTESubscriptionGetStatus
 * Signature: (I)Lorg/ocera/orte/types/Status;
 */
JNIEXPORT jobject JNICALL Java_org_ocera_orte_Subscription_jORTESubscriptionGetStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    jORTESubscriptionWaitForPublications
 * Signature: (ILorg/ocera/orte/types/NtpTime;JJ)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_Subscription_jORTESubscriptionWaitForPublications
  (JNIEnv *, jobject, jint, jobject, jlong, jlong);

/*
 * Class:     org_ocera_orte_Subscription
 * Method:    jORTESubscriptionPull
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_ocera_orte_Subscription_jORTESubscriptionPull
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
